project:
  type: website
  output-dir: docs

website:
  title: "banditkings"
  navbar:
    logo: /static/logo/logo.svg
    right:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: index.qmd
      - notes.md
      - icon: github
        href: https://github.com/banditkings
  favicon: /static/logo/logo.svg
  site-url: "https://www.nelsontang.com"
  google-analytics: 
    tracking-id: "G-R6SHJFF7F7"
    anonymize-ip: true
  cookie-consent: true
    # type: express
    # style: headline
    # palette: dark
format:
  html:
    theme: 
      light: [flatly, theme_light.scss]
      dark: [darkly, theme_dark.scss]
    linestretch: 1.6
    css: styles.css

execute:
  freeze: auto